/*
 Thomas Caulfeild
2020/03/03
This code is a multiple choice quiz about video games.
 */

/**
 *
 * @author thoma
 */
public class Mainfrm extends javax.swing.JFrame {

 
    
    
    public Mainfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpnl = new javax.swing.JPanel();
        titletxt = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        Q1D = new javax.swing.JRadioButton();
        Q1C = new javax.swing.JRadioButton();
        Q1B = new javax.swing.JRadioButton();
        Q1A = new javax.swing.JRadioButton();
        Q2D = new javax.swing.JRadioButton();
        Q2C = new javax.swing.JRadioButton();
        Q2B = new javax.swing.JRadioButton();
        Q2A = new javax.swing.JRadioButton();
        Q3A = new javax.swing.JRadioButton();
        Q3B = new javax.swing.JRadioButton();
        Q3C = new javax.swing.JRadioButton();
        Q3D = new javax.swing.JRadioButton();
        Q4D = new javax.swing.JRadioButton();
        Q4C = new javax.swing.JRadioButton();
        Q4B = new javax.swing.JRadioButton();
        Q4A = new javax.swing.JRadioButton();
        Q5D = new javax.swing.JRadioButton();
        Q5C = new javax.swing.JRadioButton();
        Q5B = new javax.swing.JRadioButton();
        Q5A = new javax.swing.JRadioButton();
        Scorebutn = new javax.swing.JButton();
        A = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        correctlbl = new javax.swing.JLabel();
        incorrectlbl = new javax.swing.JLabel();
        correctoutputlbl = new javax.swing.JLabel();
        incorrectoutputlbl = new javax.swing.JLabel();
        percentlbl = new javax.swing.JLabel();
        percentoutputlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mainpnl.setBackground(new java.awt.Color(0, 0, 0));

        titletxt.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        titletxt.setForeground(new java.awt.Color(0, 0, 240));
        titletxt.setText("Video Game Multiple Choice Quiz");

        question1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question1.setForeground(new java.awt.Color(255, 255, 255));
        question1.setText("Question 1:  What is The Most Popular Video game of 2020?");

        question2.setBackground(new java.awt.Color(255, 255, 255));
        question2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question2.setForeground(new java.awt.Color(255, 255, 255));
        question2.setText("Question 2: What Video Game Has The Most Copies Sold?");

        question3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question3.setForeground(new java.awt.Color(255, 255, 255));
        question3.setText("Question 3: What Console Was Sold The Most In 2016?");

        question4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question4.setForeground(new java.awt.Color(255, 255, 255));
        question4.setText("Question 4:  What Was The First Video Game Ever Made?");

        question5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        question5.setForeground(new java.awt.Color(255, 255, 255));
        question5.setText("Question 5: What Was The Richest Video Game Company in 2017?");

        Q1D.setBackground(new java.awt.Color(0, 0, 0));
        Q1D.setForeground(new java.awt.Color(255, 255, 255));
        Q1D.setText("Overwatch");
        Q1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1DActionPerformed(evt);
            }
        });

        Q1C.setBackground(new java.awt.Color(0, 0, 0));
        Q1C.setForeground(new java.awt.Color(255, 255, 255));
        Q1C.setText("League Of Legends");
        Q1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1CActionPerformed(evt);
            }
        });

        Q1B.setBackground(new java.awt.Color(0, 0, 0));
        Q1B.setForeground(new java.awt.Color(255, 255, 255));
        Q1B.setText("Call of Duty Modern Warfare");
        Q1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1BActionPerformed(evt);
            }
        });

        Q1A.setBackground(new java.awt.Color(0, 0, 0));
        Q1A.setForeground(new java.awt.Color(255, 255, 255));
        Q1A.setText(" Fortnite");
        Q1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1AActionPerformed(evt);
            }
        });

        Q2D.setBackground(new java.awt.Color(0, 0, 0));
        Q2D.setForeground(new java.awt.Color(255, 255, 255));
        Q2D.setText("Wii Sports");
        Q2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2DActionPerformed(evt);
            }
        });

        Q2C.setBackground(new java.awt.Color(0, 0, 0));
        Q2C.setForeground(new java.awt.Color(255, 255, 255));
        Q2C.setText("Minecraft");
        Q2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2CActionPerformed(evt);
            }
        });

        Q2B.setBackground(new java.awt.Color(0, 0, 0));
        Q2B.setForeground(new java.awt.Color(255, 255, 255));
        Q2B.setText("Grand Theft Auto");
        Q2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2BActionPerformed(evt);
            }
        });

        Q2A.setBackground(new java.awt.Color(0, 0, 0));
        Q2A.setForeground(new java.awt.Color(255, 255, 255));
        Q2A.setText("Tetris");
        Q2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2AActionPerformed(evt);
            }
        });

        Q3A.setBackground(new java.awt.Color(0, 0, 0));
        Q3A.setForeground(new java.awt.Color(255, 255, 255));
        Q3A.setText("Wii U");
        Q3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3AActionPerformed(evt);
            }
        });

        Q3B.setBackground(new java.awt.Color(0, 0, 0));
        Q3B.setForeground(new java.awt.Color(255, 255, 255));
        Q3B.setText("Nintendo 3DS");
        Q3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3BActionPerformed(evt);
            }
        });

        Q3C.setBackground(new java.awt.Color(0, 0, 0));
        Q3C.setForeground(new java.awt.Color(255, 255, 255));
        Q3C.setText("Xbox One");
        Q3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3CActionPerformed(evt);
            }
        });

        Q3D.setBackground(new java.awt.Color(0, 0, 0));
        Q3D.setForeground(new java.awt.Color(255, 255, 255));
        Q3D.setText("PlayStation 4");
        Q3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3DActionPerformed(evt);
            }
        });

        Q4D.setBackground(new java.awt.Color(0, 0, 0));
        Q4D.setForeground(new java.awt.Color(255, 255, 255));
        Q4D.setText("Space Invaders");
        Q4D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4DActionPerformed(evt);
            }
        });

        Q4C.setBackground(new java.awt.Color(0, 0, 0));
        Q4C.setForeground(new java.awt.Color(255, 255, 255));
        Q4C.setText("Pong");
        Q4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4CActionPerformed(evt);
            }
        });

        Q4B.setBackground(new java.awt.Color(0, 0, 0));
        Q4B.setForeground(new java.awt.Color(255, 255, 255));
        Q4B.setText("Pac man");
        Q4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4BActionPerformed(evt);
            }
        });

        Q4A.setBackground(new java.awt.Color(0, 0, 0));
        Q4A.setForeground(new java.awt.Color(255, 255, 255));
        Q4A.setText("Tetris");
        Q4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4AActionPerformed(evt);
            }
        });

        Q5D.setBackground(new java.awt.Color(0, 0, 0));
        Q5D.setForeground(new java.awt.Color(255, 255, 255));
        Q5D.setText("Ubisoft");
        Q5D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5DActionPerformed(evt);
            }
        });

        Q5C.setBackground(new java.awt.Color(0, 0, 0));
        Q5C.setForeground(new java.awt.Color(255, 255, 255));
        Q5C.setText("Nintendo");
        Q5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5CActionPerformed(evt);
            }
        });

        Q5B.setBackground(new java.awt.Color(0, 0, 0));
        Q5B.setForeground(new java.awt.Color(255, 255, 255));
        Q5B.setText("Electronic Arts");
        Q5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5BActionPerformed(evt);
            }
        });

        Q5A.setBackground(new java.awt.Color(0, 0, 0));
        Q5A.setForeground(new java.awt.Color(255, 255, 255));
        Q5A.setText("Activision Blizzard");
        Q5A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5AActionPerformed(evt);
            }
        });

        Scorebutn.setText("Find Your Score!!!!");
        Scorebutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScorebutnActionPerformed(evt);
            }
        });

        A.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("A");

        C.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("C");

        D.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setText("D");

        B.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("B");

        correctlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        correctlbl.setForeground(new java.awt.Color(255, 255, 255));
        correctlbl.setText("Number of Correct Answers: ");

        incorrectlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        incorrectlbl.setForeground(new java.awt.Color(255, 255, 255));
        incorrectlbl.setText("Number of Incorrect Answers: ");

        correctoutputlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        correctoutputlbl.setForeground(new java.awt.Color(255, 255, 255));
        correctoutputlbl.setText("?");

        incorrectoutputlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        incorrectoutputlbl.setForeground(new java.awt.Color(255, 255, 255));
        incorrectoutputlbl.setText("?");

        percentlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percentlbl.setForeground(new java.awt.Color(255, 255, 255));
        percentlbl.setText("Your Percentege is: ");

        percentoutputlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percentoutputlbl.setForeground(new java.awt.Color(255, 255, 255));
        percentoutputlbl.setText("?");

        javax.swing.GroupLayout MainpnlLayout = new javax.swing.GroupLayout(Mainpnl);
        Mainpnl.setLayout(MainpnlLayout);
        MainpnlLayout.setHorizontalGroup(
            MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question2)
                    .addComponent(question5)
                    .addComponent(question4)
                    .addComponent(question1)
                    .addComponent(question3))
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3A)
                            .addComponent(Q2A)
                            .addComponent(Q4A)
                            .addComponent(Q5A)
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(Q1A)))
                        .addGap(151, 151, 151)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addComponent(Q4B)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Q1B)
                                    .addComponent(Q2B)
                                    .addComponent(Q3B)
                                    .addComponent(Q5B))
                                .addGap(108, 108, 108)
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Q1C)
                                    .addComponent(Q2C)
                                    .addComponent(Q3C)
                                    .addComponent(Q4C)
                                    .addComponent(Q5C))
                                .addGap(100, 100, 100)
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Q2D, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainpnlLayout.createSequentialGroup()
                                            .addComponent(Q1D)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(MainpnlLayout.createSequentialGroup()
                                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Q3D)
                                            .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Q5D, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Q4D)))
                                        .addContainerGap(417, Short.MAX_VALUE))))))
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(B)
                        .addGap(243, 243, 243)
                        .addComponent(C)
                        .addGap(164, 164, 164)
                        .addComponent(D)
                        .addGap(459, 459, 459))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpnlLayout.createSequentialGroup()
                        .addComponent(titletxt)
                        .addGap(612, 612, 612))))
            .addGroup(MainpnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Scorebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addComponent(incorrectlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(incorrectoutputlbl))
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addComponent(correctlbl)
                                .addGap(18, 18, 18)
                                .addComponent(correctoutputlbl))))
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(699, 699, 699)
                        .addComponent(percentlbl)
                        .addGap(18, 18, 18)
                        .addComponent(percentoutputlbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainpnlLayout.setVerticalGroup(
            MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpnlLayout.createSequentialGroup()
                .addComponent(titletxt)
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpnlLayout.createSequentialGroup()
                                .addComponent(B)
                                .addGap(2, 2, 2)))
                        .addGap(5, 5, 5))
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(C)
                            .addComponent(D))
                        .addGap(7, 7, 7)))
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(question1)
                    .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Q1A)
                        .addComponent(Q1B)
                        .addComponent(Q1C)
                        .addComponent(Q1D)))
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(question2)
                                    .addComponent(Q2A)
                                    .addComponent(Q2B)
                                    .addComponent(Q2C))
                                .addGap(76, 76, 76)
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(question3)
                                    .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Q3A)
                                        .addComponent(Q3B)
                                        .addComponent(Q3C)
                                        .addComponent(Q3D)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Q4A)
                                    .addComponent(Q4B)
                                    .addComponent(Q4C)
                                    .addComponent(Q4D)))
                            .addGroup(MainpnlLayout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(question4))))
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Q2D)))
                .addGap(86, 86, 86)
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question5)
                    .addComponent(Q5A)
                    .addComponent(Q5B)
                    .addComponent(Q5C)
                    .addComponent(Q5D))
                .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correctlbl)
                            .addComponent(correctoutputlbl))
                        .addGap(35, 35, 35)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectlbl)
                            .addComponent(incorrectoutputlbl)))
                    .addGroup(MainpnlLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(MainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Scorebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentlbl)
                            .addComponent(percentoutputlbl))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScorebutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScorebutnActionPerformed
             
        int correct = 0;
        int incorrect = 0;
        double percent;
        int totalQ = 5;
        
        
        
        {  
        if(Q1A.isSelected())
        {        
         correct= correct+1;     
        }
        else if(Q1B.isSelected())
        {   
         incorrect = incorrect + 1 ;       
        }
        else if (Q1C.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
          else if (Q1D.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
         
        }
          
        {  
          
          if (Q2A.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q2B.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }   
        else if (Q2C.isSelected())
        {    
        correct= correct+1;
        }   
        else if (Q2D.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
        
        }
        
        { 
         if (Q3A.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q3B.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q3C.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q3D.isSelected())
        {    
        correct= correct+1 ;
        }
           
        } 
           
        {
        
        if (Q4A.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q4B.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q4C.isSelected())
        {    
        correct = correct + 1 ;
        }
           else if (Q4D.isSelected())
        {    
        incorrect= incorrect+1 ;
        }
           
        }  
         
        {
        
        
        if (Q5A.isSelected())
        {    
        correct= correct+1;
        }
           else if (Q5B.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q5C.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
           else if (Q5D.isSelected())
        {    
        incorrect = incorrect + 1 ;
        }
        
        }
                
        correctoutputlbl.setText(String.valueOf(correct));
        
        incorrectoutputlbl.setText(String.valueOf(incorrect));
        
        
        
        
       percent = (correct/5) * 100 ;
              
        
        percentoutputlbl.setText(String.valueOf(percent));
        
        
        
        

    }//GEN-LAST:event_ScorebutnActionPerformed

    private void Q5AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5AActionPerformed
                
        if (Q5A.isSelected());
        {
            Q5B.setSelected(false);
            Q5D.setSelected(false);
            Q5C.setSelected(false);
        }
        
     
                
    }//GEN-LAST:event_Q5AActionPerformed

    private void Q5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5BActionPerformed

        if (Q5B.isSelected());
        {
            Q5A.setSelected(false);
            Q5D.setSelected(false);
            Q5C.setSelected(false);
        }
         
    }//GEN-LAST:event_Q5BActionPerformed

    private void Q5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5CActionPerformed
        if (Q5C.isSelected());
        {
            Q5B.setSelected(false);
            Q5D.setSelected(false);
            Q5A.setSelected(false);
        }
    }//GEN-LAST:event_Q5CActionPerformed

    private void Q5DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5DActionPerformed
        if (Q5D.isSelected());
        {
            Q5B.setSelected(false);
            Q5A.setSelected(false);
            Q5C.setSelected(false);
        }
    }//GEN-LAST:event_Q5DActionPerformed

    private void Q4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4AActionPerformed
        if (Q4A.isSelected());
        {
            Q4B.setSelected(false);
            Q4C.setSelected(false);
            Q4D.setSelected(false);
        }

    }//GEN-LAST:event_Q4AActionPerformed

    private void Q4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4BActionPerformed
        if (Q4B.isSelected());
        {
            Q4A.setSelected(false);
            Q4C.setSelected(false);
            Q4D.setSelected(false);
        }

    }//GEN-LAST:event_Q4BActionPerformed

    private void Q4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4CActionPerformed
        if (Q4C.isSelected());
        {
            Q4B.setSelected(false);
            Q4A.setSelected(false);
            Q4D.setSelected(false);
        }

    }//GEN-LAST:event_Q4CActionPerformed

    private void Q4DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4DActionPerformed
        if (Q4D.isSelected());
        {
            Q4B.setSelected(false);
            Q4A.setSelected(false);
            Q4C.setSelected(false);
        }

    }//GEN-LAST:event_Q4DActionPerformed

    private void Q3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3DActionPerformed
        if (Q3D.isSelected());
        {
            Q3B.setSelected(false);
            Q3C.setSelected(false);
            Q3A.setSelected(false);
        }
    }//GEN-LAST:event_Q3DActionPerformed

    private void Q3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3CActionPerformed
        if (Q3C.isSelected());
        {
            Q3B.setSelected(false);
            Q3A.setSelected(false);
            Q3D.setSelected(false);
        }
    }//GEN-LAST:event_Q3CActionPerformed

    private void Q3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3BActionPerformed
        if (Q3B.isSelected());
        {
            Q3A.setSelected(false);
            Q3C.setSelected(false);
            Q3D.setSelected(false);
        }
    }//GEN-LAST:event_Q3BActionPerformed

    private void Q3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3AActionPerformed
        if (Q3A.isSelected());
        {
            Q3B.setSelected(false);
            Q3C.setSelected(false);
            Q3D.setSelected(false);
        }

    }//GEN-LAST:event_Q3AActionPerformed

    private void Q2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2AActionPerformed

        if (Q2A.isSelected());
        {
            Q2B.setSelected(false);
            Q2C.setSelected(false);
            Q2D.setSelected(false);
        }

    }//GEN-LAST:event_Q2AActionPerformed

    private void Q2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2BActionPerformed

        if (Q2B.isSelected());
        {
            Q2A.setSelected(false);
            Q2C.setSelected(false);
            Q2D.setSelected(false);
        }

    }//GEN-LAST:event_Q2BActionPerformed

    private void Q2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2CActionPerformed
        if (Q2C.isSelected());
        {
            Q2A.setSelected(false);
            Q2B.setSelected(false);
            Q2D.setSelected(false);
        }

    }//GEN-LAST:event_Q2CActionPerformed

    private void Q2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2DActionPerformed
        if (Q2D.isSelected());
        {
            Q2B.setSelected(false);
            Q2C.setSelected(false);
            Q2A.setSelected(false);
        }

    }//GEN-LAST:event_Q2DActionPerformed

    private void Q1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1AActionPerformed

        if (Q1A.isSelected());
        {
            Q1B.setSelected(false);
            Q1C.setSelected(false);
            Q1D.setSelected(false);
        }
        

    }//GEN-LAST:event_Q1AActionPerformed

    private void Q1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1BActionPerformed
        if (Q1B.isSelected());
        {
            Q1A.setSelected(false);
            Q1C.setSelected(false);
            Q1D.setSelected(false);
        }

    }//GEN-LAST:event_Q1BActionPerformed

    private void Q1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1CActionPerformed

        if (Q1C.isSelected());
        {
            Q1A.setSelected(false);
            Q1B.setSelected(false);
            Q1D.setSelected(false);
        }

    }//GEN-LAST:event_Q1CActionPerformed

    private void Q1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1DActionPerformed

        if (Q1D.isSelected());
        {
            Q1A.setSelected(false);
            Q1C.setSelected(false);
            Q1B.setSelected(false);
        }

    }//GEN-LAST:event_Q1DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mainfrm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JPanel Mainpnl;
    private javax.swing.JRadioButton Q1A;
    private javax.swing.JRadioButton Q1B;
    private javax.swing.JRadioButton Q1C;
    private javax.swing.JRadioButton Q1D;
    private javax.swing.JRadioButton Q2A;
    private javax.swing.JRadioButton Q2B;
    private javax.swing.JRadioButton Q2C;
    private javax.swing.JRadioButton Q2D;
    private javax.swing.JRadioButton Q3A;
    private javax.swing.JRadioButton Q3B;
    private javax.swing.JRadioButton Q3C;
    private javax.swing.JRadioButton Q3D;
    private javax.swing.JRadioButton Q4A;
    private javax.swing.JRadioButton Q4B;
    private javax.swing.JRadioButton Q4C;
    private javax.swing.JRadioButton Q4D;
    private javax.swing.JRadioButton Q5A;
    private javax.swing.JRadioButton Q5B;
    private javax.swing.JRadioButton Q5C;
    private javax.swing.JRadioButton Q5D;
    private javax.swing.JButton Scorebutn;
    private javax.swing.JLabel correctlbl;
    private javax.swing.JLabel correctoutputlbl;
    private javax.swing.JLabel incorrectlbl;
    private javax.swing.JLabel incorrectoutputlbl;
    private javax.swing.JLabel percentlbl;
    private javax.swing.JLabel percentoutputlbl;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel titletxt;
    // End of variables declaration//GEN-END:variables
}
